name: Build Docker 

on: 
  push:
    # paths:
    # - 'docker/**'

jobs:

  build:
    name: Build & Publish Docker

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set IMAGE_TAG env 
      run: echo IMAGE_TAG=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    - name: Append latest if main branches # env '${IMAGE_TAG},latest'
      if: endsWith(github.ref, 'main')
      run: echo IMAGE_TAG=${IMAGE_TAG},latest >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - name: Build & Publish to Github Container Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.actor }}/${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: docker/dev/Dockerfile
        snapshot: false
        tags: "${{ env.IMAGE_TAG }}"

